name: $(Build.BuildId)
trigger:
  batch: true
  branches:
    include: 
    - '*'
  tags:
    include:
    - '*'

jobs:
  - job: BuildJavaScript
    displayName: Build JavaScript
    pool:
      vmName: ubuntu-18.04
      demands:
      - npm
    
    steps:
    - task: Npm@1
      displayName: 'npm cache clean --force'
      inputs:
        command: custom
        verbose: false
        customCommand: 'cache clean --force'

    - task: Npm@1
      displayName: 'npm install'

    - task: Npm@1
      displayName: 'npm run lint:ci'
      inputs:
        command: custom
        verbose: false
        customCommand: 'run lint:ci'
    
    - task: Npm@1
      displayName: 'npm run build'
      inputs:
        command: custom
        verbose: false
        customCommand: 'run build'

    - task: Npm@1
      displayName: 'run demo builds'
      inputs:
        command: custom
        verbose: false
        customCommand: 'npm run start:example:mini-editor'
        